# syntax=docker/dockerfile:1.4
FROM golang:1.24

ENV DEBIAN_FRONTEND=noninteractive
ENV GO_ENV=development

# Install Air
RUN apt-get update && \
    apt-get install -y git && \
    go install github.com/air-verse/air@latest

WORKDIR /app

# Copy modules, then code
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Expose your HTTP/gRPC port
EXPOSE 8080

# Launch via Air
CMD ["air"]
